/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Family } from './family';
import { Child } from './child';


export interface Car { 
    id?: number;
    children?: Array<Child>;
    family?: Family;
}

