/**
 * carpool-back API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AbsenceDays } from './absence-days';


export interface Child {
    id?: number;
    name?: string;
    absenceDays?: AbsenceDays[];
}

