/**
 * carpool-back API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Requirement } from './requirement';
import { Child } from './child';


export interface Family {
    id?: number;
    name?: string;
    carCapacity?: number;
    children?: Array<Child>;
    requirements?: Requirement[];
}

