/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Schedule } from './schedule';


export interface FullSchedule { 
    id?: number;
    oddSchedule?: Schedule;
    evenSchedule?: Schedule;
}

