/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekDay } from './week-day';
import { Family } from './family';
import { TimeSlot } from './time-slot';
import { WeekType } from './week-type';


export interface Requirement { 
    id?: number;
    timeSlot?: TimeSlot;
    weekDay?: WeekDay;
    weekType?: WeekType;
    family?: Family;
}
export namespace Requirement {
}


