/**
 * carpool-back API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Trip } from './trip';


export interface Schedule {
    id?: number;
    trips?: Trip[];
}

