/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Trip } from './trip';
import { WeekType } from './week-type';


export interface Schedule { 
    id?: number;
    weekType?: WeekType;
    trips?: Array<Trip>;
}
export namespace Schedule {
}


