/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TimeSlot = {
    Morning: 'MORNING',
    Evening: 'EVENING'
} as const;
export type TimeSlot = typeof TimeSlot[keyof typeof TimeSlot];

