/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekDay } from './week-day';
import { Family } from './family';
import { TimeSlot } from './time-slot';
import { Child } from './child';


export interface Trip { 
    id?: number;
    weekDay?: WeekDay;
    timeSlot?: TimeSlot;
    driver?: Family;
    children?: Set<Child>;
}
export namespace Trip {
}


