/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WeekType = {
    Even: 'EVEN',
    Odd: 'ODD'
} as const;
export type WeekType = typeof WeekType[keyof typeof WeekType];

