/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WeekDay = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY'
} as const;
export type WeekDay = typeof WeekDay[keyof typeof WeekDay];

