export * from './family-resource.service';
import { FamilyResourceService } from './family-resource.service';
export * from './family-resource.serviceInterface';
export * from './full-schedule-resource.service';
import { FullScheduleResourceService } from './full-schedule-resource.service';
export * from './full-schedule-resource.serviceInterface';
export * from './schedule-stat-resource.service';
import { ScheduleStatResourceService } from './schedule-stat-resource.service';
export * from './schedule-stat-resource.serviceInterface';
export const APIS = [FamilyResourceService, FullScheduleResourceService, ScheduleStatResourceService];
