/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Family } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FamilyResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Families
     * 
     */
    familyGet(extraHttpRequestParams?: any): Observable<Array<Family>>;

    /**
     * Get Family
     * 
     * @param id 
     */
    familyIdGet(id: number, extraHttpRequestParams?: any): Observable<Family>;

    /**
     * Update Family
     * 
     * @param id 
     */
    familyIdPut(id: number, extraHttpRequestParams?: any): Observable<Family>;

    /**
     * Create Family
     * 
     * @param family 
     */
    familyPost(family: Family, extraHttpRequestParams?: any): Observable<Family>;

}
