/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Family } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FamilyResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Count
     * 
     */
    familyCountGet(extraHttpRequestParams?: any): Observable<number>;

    /**
     * List
     * 
     * @param carCapacity 
     * @param id 
     * @param name 
     * @param namedQuery 
     * @param page 
     * @param size 
     * @param sort 
     */
    familyGet(carCapacity?: number, id?: number, name?: string, namedQuery?: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Array<Family>>;

    /**
     * Delete
     * 
     * @param id 
     */
    familyIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get
     * 
     * @param id 
     */
    familyIdGet(id: number, extraHttpRequestParams?: any): Observable<Family>;

    /**
     * Update
     * 
     * @param id 
     * @param family 
     */
    familyIdPut(id: number, family: Family, extraHttpRequestParams?: any): Observable<Family>;

    /**
     * Add
     * 
     * @param family 
     */
    familyPost(family: Family, extraHttpRequestParams?: any): Observable<Family>;

}
