/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FullSchedule } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FullScheduleResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Count
     * 
     */
    fullScheduleCountGet(extraHttpRequestParams?: any): Observable<number>;

    /**
     * List
     * 
     * @param id 
     * @param namedQuery 
     * @param page 
     * @param size 
     * @param sort 
     */
    fullScheduleGet(id?: number, namedQuery?: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Array<FullSchedule>>;

    /**
     * Delete
     * 
     * @param id 
     */
    fullScheduleIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get
     * 
     * @param id 
     */
    fullScheduleIdGet(id: number, extraHttpRequestParams?: any): Observable<FullSchedule>;

    /**
     * Update
     * 
     * @param id 
     * @param fullSchedule 
     */
    fullScheduleIdPut(id: number, fullSchedule: FullSchedule, extraHttpRequestParams?: any): Observable<FullSchedule>;

    /**
     * Add
     * 
     * @param fullSchedule 
     */
    fullSchedulePost(fullSchedule: FullSchedule, extraHttpRequestParams?: any): Observable<FullSchedule>;

}
