/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Requirement } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RequirementResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Count
     * 
     */
    requirementCountGet(extraHttpRequestParams?: any): Observable<number>;

    /**
     * List
     * 
     * @param familyId 
     * @param id 
     * @param namedQuery 
     * @param page 
     * @param size 
     * @param sort 
     */
    requirementGet(familyId?: number, id?: number, namedQuery?: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Array<Requirement>>;

    /**
     * Delete
     * 
     * @param id 
     */
    requirementIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get
     * 
     * @param id 
     */
    requirementIdGet(id: number, extraHttpRequestParams?: any): Observable<Requirement>;

    /**
     * Update
     * 
     * @param id 
     * @param requirement 
     */
    requirementIdPut(id: number, requirement: Requirement, extraHttpRequestParams?: any): Observable<Requirement>;

    /**
     * Add
     * 
     * @param requirement 
     */
    requirementPost(requirement: Requirement, extraHttpRequestParams?: any): Observable<Requirement>;

}
