/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Stats } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ScheduleStatResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Stats
     * 
     * @param id 
     */
    scheduleIdStatsGet(id: number, extraHttpRequestParams?: any): Observable<Array<Stats>>;

}
