/**
 * carpool-back API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FullSchedule } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ScheduleResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Generate Full Schedule
     * 
     */
    scheduleGet(extraHttpRequestParams?: any): Observable<FullSchedule>;

}
